### ISSUE TITLE
lua: ./9p.lua:138: attempt to get length of local 'from' (a nil value)

### ISSUE THREAD

**Issue by metacoma** [iru-/lua9p#2]
There are two public 9p fileservers (without any authentication) and hosted by different OS/Platforms 
- tcp!9p.io!564 (9front OS)
- tcp!registry.demo.metacoma.io!30099 (Inferno OS)

1. If we connect to `tcp!9p.io!564` and call  `Twalk ./` - everything is fine
2. If we connect to `tcp!9p.io!564` and call `Twalk /` then get error `lua: ./9p.lua:138: attempt to get length of local 'from' (a nil value)`
3. If we connect to  `tcp!registry.demo!metacoma.io!30099` and call `Twalk ./` then get error `lua: ./9p.lua:118: file does not exist`
4. If we connect to `tcp!registry.demo!metacoma.io!30099` and call `Twalk /` then get error `lua: ./9p.lua:138: attempt to get length of local 'from' (a nil value)`
5. If we connect to `tcp!registry.demo.metacoma.io!30099` and call  `Twalk ../` - everything is fine
6. If we connect to `tcp!9p.io!564` and call  `Twalk ../` - everything is fine, but the result is different from `Twalk ./` 

How to call properly  Twalk against root(/) path of these fileservers in the same way? 

Steps to reproduce: 

```bash
$ git clone -b 9p_walk_bug github.com/metacoma/lua9p
$ cd lua9p
#
# 1 case
#
$ lua ./tcp_testclient.lua 'tcp!9p.io!564' './'                 
Connecting to tcp!9p.io!564
Walking on ./
#
# 2 case
# 
$ lua ./tcp_testclient.lua 'tcp!9p.io!564' '/'
Connecting to tcp!9p.io!564
Walking on /
lua: ./9p.lua:138: attempt to get length of local 'from' (a nil value)
#
# 3 case
# 
$ lua ./tcp_testclient.lua 'tcp!registry.demo.metacoma.io!30099' '/'  
$ Connecting to tcp!registry.demo.metacoma.io!30099
Walking on /
lua: ./9p.lua:118: file does not exist
#
# 4 case
# 
$ lua ./tcp_testclient.lua 'tcp!registry.demo.metacoma.io!30099' './'  
$ Connecting to tcp!registry.demo.metacoma.io!30099
Walking on ./
lua: ./9p.lua:138: attempt to get length of local 'from' (a nil value)
#
# 5 case
# 
$ lua ./tcp_testclient.lua 'tcp!registry.demo.metacoma.io!30099' '../'
Connecting to tcp!registry.demo.metacoma.io!30099
Walking on ../
Ok
#
# 6 case
# 
$ lua ./tcp_testclient.lua 'tcp!9p.io!564' '../'                 
Connecting to tcp!9p.io!564
Walking on ../
Ok
```

**Comment by iru-** [comment]
Good catch, @metacoma!

I couldn't clone your `9p_walk_bug` branch, but I wrote two scripts to reproduce the issue (https://gist.github.com/iru-/717ab72326d2f9889a5ab2aae94aa51e). See their output below:

```
% ./test_walk_bug.sh
case 1
connected to tcp!9p.io!564
walking on "./"
ok! "./" on fid 1

case 2
connected to tcp!9p.io!564
walking on "/"
./9p.lua:138: attempt to get length of a nil value (local 'from')

case 3
connected to tcp!registry.demo.metacoma.io!30099
walking on "/"
./9p.lua:138: attempt to get length of a nil value (local 'from')

case 4
connected to tcp!registry.demo.metacoma.io!30099
walking on "./"
./9p.lua:118: file does not exist

case 5
connected to tcp!registry.demo.metacoma.io!30099
walking on "../"
ok! "../" on fid 1

case 6
connected to tcp!9p.io!564
walking on "../"
ok! "../" on fid 1

```

The bug stems from incorrectly breaking paths into path elements for Twalk (see https://github.com/iru-/lua9p/blob/07c4af26488e221126d1a7d8091c2f3a156c35fe/9p.lua#L307).

The fix is available at https://github.com/iru-/lua9p/pull/4. The new test output is:
```
% ./test_walk_bug.sh
case 1
connected to tcp!9p.io!564
walking on "./"
ok! "./" on fid 1

case 2
connected to tcp!9p.io!564
walking on "/"
./9p.lua:118: file does not exist

case 3
connected to tcp!registry.demo.metacoma.io!30099
walking on "/"
./9p.lua:118: file does not exist

case 4
connected to tcp!registry.demo.metacoma.io!30099
walking on "./"
./9p.lua:118: file does not exist

case 5
connected to tcp!registry.demo.metacoma.io!30099
walking on "../"
ok! "../" on fid 1

case 6
connected to tcp!9p.io!564
walking on "../"
ok! "../" on fid 1

```

Do you confirm the fix works on your side?

**Comment by metacoma** [comment]
hey @iru- thank you for your rapid answer! 

Sorry about the `tcp_testclient.lua`, I pushed it in the wrong place :( https://github.com/metacoma/lua9p/blob/a67faf06e616397339bd24285f87b26dea856e78/tcp_testclient.lua

Your fix helps, the problem `attempt to get length of local 'from' (a nil value)` is gone.

but I still don't understand, how to properly "generate" Twalk packet for walking "root(/)" on `tcp!9p.io!564` and `tcp!registry.demo.metacoma.io!30099` in the same way

**Comment by iru-** [comment]
What you want is most easily achieved by `conn:clone(conn.rootfid, newfid)`, where `newfid` has already been allocated.

Even though not explicitly defined, in 9P parlance a "clone" is a walk with no paths to be walked to. The effect of this is to clone/duplicate the old fid into the new fid in the server and the client. You can think of it as the 9P analogous to the `dup2` system call.

Let me know if that works for you. It worked here for both `9p.io` and `registry.demo.metacoma.io`

**Comment by metacoma** [comment]
Thank you @iru- it works!

![screencast](https://user-images.githubusercontent.com/5146707/103463648-47f22380-4d47-11eb-80cb-9fc22552ddfe.png)

Also thanks to @dievri https://github.com/9mine/9mine/compare/a0d76fd6496c832af72502d33bfa5f89bf35b81f...3346ddfa999b4b00825881b3573714e50ff32a33

**Comment by iru-** [comment]
Awesome! Thanks again, @metacoma!

Since the bug has been fixed in https://github.com/iru-/lua9p/commit/3af266d9449b563710034e571d4bab10275af2d6 and your question has been answered, I'm closing the issue.
